module.exports.DEFAULT_EMAIL_ADDRESS = 'noreply@cartradez.com';
module.exports.DEFAULT_EMAIL_NAME = 'Car Tradez';

module.exports.SENDGRID_RESET_LOGIN_TEMPLATE_ID =
  'SENDGRID_RESET_LOGIN_TEMPLATE_ID';

module.exports.SENDGRID_VERIFY_USER_TEMPLATE_ID =
  'SENDGRID_VERIFY_USER_TEMPLATE_ID';

module.exports.SENDGRID_INVITE_USER_TEMPLATE_ID =
  'SENDGRID_INVITE_USER_TEMPLATE_ID';
